### PR TITLE
Update gitignore and add a blurb on top of files generated by build.rs

### PR DESCRIPTION
**Pull request by ckoparkar**

### CODE REVIEW

**Comment by ckoparkar** [comment]
I'm not so sure about all the `build.rs` changes. There's a lot of code duplication and adding the corresponding files to `.gitignore` is sufficient. /cc @rrnewton @wangbj

**Comment by wangbj** [comment]
Thanks a lot for the PR, is there any reason to use fixed name instead of using `mktemp`?

**Comment by ckoparkar** [comment]
Not really. I wanted to avoid adding a dev dependency just for creating a temporary file which we have to rename hand anyway. I can update this to use the proper crate too.

**Comment by wangbj** [comment]
`build-dependencies` is used by `build.rs` only, it seems better to use `mktemp` instead of hard code the filename. Others look good.

**Comment by ckoparkar** [comment]
@wangbj done :) It uses [tempfile](https://crates.io/crates/tempfile) now.

**Comment by wangbj** [comment]
Thanks!

**Pull request merged**
